---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloudservices/ci
    tag: latest
inputs:
  - name: git-repo
outputs:
  - name: distribution-repository
caches:
  - path: maven
  - path: gradle
run:
  path: git-repo/ci/scripts/build-project.sh
