---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((docker-hub-organization))/release-ci-image
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((branch))
inputs:
  - name: git-repo
  - name: artifactory-repo
outputs:
  - name: version
params:
  ARTIFACTORY_SERVER: ((artifactory-server))
  ARTIFACTORY_USERNAME: ((scs-artifactory-username))
  ARTIFACTORY_PASSWORD: ((scs-artifactory-password))
  BINTRAY_SUBJECT: ((bintray-subject))
  BINTRAY_REPO: ((bintray-repo))
  BINTRAY_USERNAME: ((bintray-username))
  BINTRAY_API_KEY: ((bintray-api-key))
  BINTRAY_PACKAGE: ((bintray-package))
  BINTRAY_DISTRIBUTION_REPO: ((bintray-distribution-repo))
run:
  path: git-repo/ci/scripts/distribute.sh
