---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloudservices/ci
    tag: latest
inputs:
  - name: git-repo
  - name: artifactory-repo
outputs:
  - name: version
params:
  RELEASE_TYPE: ((release-type))
  ARTIFACTORY_SERVER: ((artifactory-server))
  ARTIFACTORY_USERNAME: ((scs-artifactory-username))
  ARTIFACTORY_PASSWORD: ((scs-artifactory-password))
run:
  path: git-repo/ci/scripts/promote.sh
