---
platform: linux
inputs:
  - name: git-repo
  - name: artifactory-repo
outputs:
  - name: version
params:
  RELEASE_TYPE:
  ARTIFACTORY_SERVER: ((artifactory-server))
  ARTIFACTORY_USERNAME: ((scs-artifactory-username))
  ARTIFACTORY_PASSWORD: ((scs-artifactory-password))
run:
  path: git-repo/ci/scripts/promote.sh
