---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloudservices/ci
    tag: latest
inputs:
  - name: git-repo
outputs:
  - name: stage-git-repo
  - name: distribution-repository
params:
  RELEASE_TYPE: ((release-type))
caches:
  - path: maven
  - path: gradle
run:
  path: git-repo/ci/scripts/stage.sh
