---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((docker-hub-organization))/release-ci-image
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((branch))
inputs:
  - name: git-repo
outputs:
  - name: stage-git-repo
  - name: distribution-repository
params:
  RELEASE_TYPE:
caches:
  - path: maven
  - path: gradle
run:
  path: git-repo/ci/scripts/stage.sh
