---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((docker-hub-organization))/release-ci-image
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((branch))
inputs:
  - name: git-repo
  - name: artifactory-repo
params:
  BINTRAY_REPO:
  BINTRAY_SUBJECT:
  BINTRAY_USERNAME:
  BINTRAY_API_KEY:
  BINTRAY_PACKAGE:
  SONATYPE_USER_TOKEN:
  SONATYPE_PASSWORD_TOKEN:
run:
  path: git-repo/ci/scripts/sync-to-maven-central.sh
