---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloudservices/ci
    tag: latest
inputs:
  - name: git-repo
  - name: artifactory-repo
params:
  BINTRAY_REPO: ((bintray-repo))
  BINTRAY_SUBJECT: ((bintray-subject))
  BINTRAY_USERNAME: ((bintray-username))
  BINTRAY_API_KEY: ((bintray-api-key))
  BINTRAY_PACKAGE: ((bintray-package))
  SONATYPE_USER_TOKEN: ((sonatype-user-token))
  SONATYPE_PASSWORD_TOKEN: ((sonatype-user-token-password))
run:
  path: git-repo/ci/scripts/sync-to-maven-central.sh
