---
aliases:
  - &slack-failure-notification
    put: alert
    params:
      icon_emoji: ":animal:"
      username: concourse
      channel: {{scs-slack-failure-channel}}
      text: <!here> Build <https://scs.ci.springapps.io/builds/$BUILD_ID|$BUILD_NAME> of job $BUILD_JOB_NAME in the $BUILD_PIPELINE_NAME pipeline has failed!

jobs:
  - name: build
    serial: true
    public: true
    plan:
    - get: git-repo
      trigger: true
    - do:
      - task: build-project
        file: git-repo/ci/tasks/build-project.yml
        vars:
          branch: ((branch))
    - put: artifactory-repo
      params: &artifactory-params
        repo: libs-snapshot-local
        folder: distribution-repository
        build_uri: "https://scs.ci.springapps.io/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
        build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
        disable_checksum_uploads: true
    on_failure:
      *slack-failure-notification

  - name: stage-milestone
    serial: true
    plan:
      - get: git-repo
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        vars:
          branch: ((branch))
          release-type: M
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo
        params:
          repository: stage-git-repo
  - name: stage-rc
    serial: true
    plan:
      - get: git-repo
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        vars:
          branch: ((branch))
          release-type: RC
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo
        params:
          repository: stage-git-repo
  - name: stage-release
    serial: true
    plan:
      - get: git-repo
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        vars:
          branch: ((branch))
          release-type: RELEASE
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo
        params:
          repository: stage-git-repo
  - name: promote-milestone
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [stage-milestone]
        params:
          save_build_info: true
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        vars:
          branch: ((branch))
          release-type: M
          artifactory-server: ((artifactory-server))
  - name: promote-rc
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [stage-rc]
        params:
          save_build_info: true
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        vars:
          branch: ((branch))
          release-type: RC
          artifactory-server: ((artifactory-server))
  - name: promote-release
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [stage-release]
        params:
          save_build_info: true
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        vars:
          branch: ((branch))
          release-type: RELEASE
          artifactory-server: ((artifactory-server))
  - name: distribute-release
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [promote-release]
        params:
          save_build_info: true
      - task: distribute
        file: git-repo/ci/tasks/distribute.yml
        vars:
          branch: ((branch))
          artifactory-server: ((artifactory-server))
          bintray-subject: ((bintray-subject))
          bintray-repo: ((bintray-repo))
          bintray-package: ((bintray-package))
          bintray-distribution-repo: ((bintray-distribution-repo))
  - name: sync-to-maven-central
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [distribute-release]
        params:
          save_build_info: true
      - task: sync-to-maven-central
        file: git-repo/ci/tasks/sync-to-maven-central.yml
        vars:
          branch: ((branch))
          bintray-subject: ((bintray-subject))
          bintray-repo: ((bintray-repo))
          bintray-package: ((bintray-package))

resource_types:
  - name: artifactory-resource
    type: docker-image
    source:
      repository: springio/artifactory-resource
      tag: 0.0.7
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: git-repo
    type: git
    source:
      uri: ((github-repo))
      username: ((github-username))
      password: ((github-password))
      branch: ((branch))
      ignore_paths: ["ci/images/*"]
  - name: artifactory-repo
    type: artifactory-resource
    source:
      uri: ((artifactory-server))
      username: ((scs-artifactory-username))
      password: ((scs-artifactory-password))
      build_name: ((build-name))
  - name: alert
    type: slack-notification
    source:
      url: ((scs-slack-webhook))
groups:
  - name: "Build"
    jobs: ["build"]
  - name: "Release"
    jobs: ["stage-milestone", "stage-rc", "stage-release", "promote-milestone", "promote-rc", "promote-release", "distribute-release", "sync-to-maven-central"]
